# ----------------------------------------------------------------------------
#  Copyright (c) 2018 WSO2, Inc. http://www.wso2.org
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
# ----------------------------------------------------------------------------

wso2_group: wso2
wso2_user: wso2carbon
product_name: wso2am-analytics
product_version: 3.2.0
target: /mnt
product_package_location: files
misc_file_location: "{{ product_package_location }}/misc"
misc_file_copy_location: "{{ target }}/misc"
security_file_location: "{{ product_package_location }}/security"
#jdbc_driver: mysql-connector-java-5.1.47-bin.jar

# Performance tuning configurations
enable_performance_tuning: false
performance_tuning_file_list:
  - { src: '{{ product_package_location }}/system/etc/sysctl.conf',
      dest: '/etc/sysctl.conf' }
  - { src: '{{ product_package_location }}/system/etc/security/limits.conf',
      dest: '/etc/security/limits.conf' }

# If custom keystores and trsustrores are need to be added, uncomment the below list
# Add the required files under files/security/<product-home>/<path-to-file>
# A sample is given below
# security_file_list:
#   - { src: '{{ security_file_location }}/wso2am-analytics/client-truststore.jks',
#       dest: '{{ carbon_home }}/resources/security/client-truststore.jks' }
#   - { src: '{{ security_file_location }}/wso2am-analytics/wso2carbon.jks',
#       dest: '{{ carbon_home }}/resources/security/wso2carbon.jks' }

# Uncomment and add any miscellaneous files you need to copy
# A sample is given below
# misc_file_list:
#   - { src: '{{ misc_file_location }}/apimcli.zip',
#       dest: '{{ misc_file_copy_location }}/apimcli.zip' }

# Set the location the product packages should reside in (eg: "local" in the /files directory, "remote" in a remote location)
pack_location: local
#pack_location: remote
#remote_jdk: "<URL_TO_JDK_FILE>"
#remote_pack: "<URL_TO_APIM_ANALYTICS_PACK>"

# JDK Distributions
setup_java_enabled: true #If this is set to false java_home variable below needs to be specified.
jdk_name: amazon-corretto-8-x64-linux-jdk
java_dir: /opt
java_symlink: "{{ java_dir }}/java"
java_home: "{{ java_dir }}/{{ jdk_name }}"

baseUrl: https://localhost:9643 # Analytics URL
publisherUrl: https://localhost:9443 # Publisher URL
devPortalUrl: https://localhost:9443 # Devportal URL
admin_service_username: admin
admin_service_password: admin
keymanager_username: admin
keymanager_password: admin

# Database configurations
wso2_metrics_db_url: jdbc:h2:${sys:carbon.home}/wso2/dashboard/database/metrics;AUTO_SERVER=TRUE
wso2_metrics_db_username: wso2carbon
wso2_metrics_db_password: wso2carbon
wso2_metrics_db_driver: org.h2.Driver
wso2_metrics_db_test_query: SELECT 1

wso2_permissions_db_url: jdbc:h2:${sys:carbon.home}/wso2/${sys:wso2.runtime}/database/PERMISSION_DB;IFEXISTS=TRUE;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000;MVCC=TRUE
wso2_permissions_db_username: wso2carbon
wso2_permissions_db_password: wso2carbon
wso2_permissions_db_driver: org.h2.Driver
wso2_permissions_db_test_query: SELECT 1

message_tracing_db_url: jdbc:h2:${sys:carbon.home}/wso2/dashboard/database/MESSAGE_TRACING_DB;AUTO_SERVER=TRUE
message_tracing_db_username: wso2carbon
message_tracing_db_password: wso2carbon
message_tracing_db_driver: org.h2.Driver
message_tracing_db_test_query: SELECT 1

apim_analytics_db_url: jdbc:h2:${sys:carbon.home}/../../apim-analytics-worker/wso2am-analytics-{{ product_version }}/wso2/database/WSO2AM_STATS_DB;AUTO_SERVER=TRUE
apim_analytics_db_username: wso2carbon
apim_analytics_db_password: wso2carbon
apim_analytics_db_driver: org.h2.Driver
apim_analytics_db_test_query: SELECT 1

wso2am_mgw_analytics_db_url: jdbc:h2:${sys:carbon.home}/wso2/worker/database/WSO2AM_MGW_ANALYTICS_DB;AUTO_SERVER=TRUE
wso2am_mgw_analytics_db_username: wso2carbon
wso2am_mgw_analytics_db_password: wso2carbon
wso2am_mgw_analytics_db_driver: org.h2.Driver
wso2am_mgw_analytics_db_test_query: SELECT 1

cluster_db_url: jdbc:h2:${sys:carbon.home}/wso2/${sys:wso2.runtime}/database/WSO2_CLUSTER_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000;AUTO_SERVER=TRUE
cluster_db_username: wso2carbon
cluster_db_password: wso2carbon
cluster_db_driver: com.mysql.jdbc.Driver
cluster_db_test_query: SELECT 1

business_rules_db_url: jdbc:h2:${sys:carbon.home}/wso2/${sys:wso2.runtime}/database/BUSINESS_RULES_DB;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=60000;MVCC=TRUE
business_rules_db_username: wso2carbon
business_rules_db_password: wso2carbon
business_rules_db_driver: org.h2.Driver
business_rules_db_test_query: SELECT 1

am_db_url: jdbc:h2:${sys:carbon.home}/../../apim/wso2am-{{ product_version }}/repository/database/WSO2AM_DB;AUTO_SERVER=TRUE
am_db_username: wso2carbon
am_db_password: wso2carbon
am_db_driver: org.h2.Driver
am_test_query: SELECT 1

state_persistence_enabled: 'false'
state_persistence_interval: 1
state_persistence_revisions: 2
deployment_type: none

#deployment_type: ha
#eventSyncServer_host: localhost
#eventSyncServer_port: 9893
#eventSyncServer_advertised_host: localhost
#eventSyncServer_advertised_port: 9893

# Note: In below section if secure-vault is enabled you need to update the secrests.properties file and and
# the deployment.yaml.j2 accordingly accomodate secured values. 

#deployment_type: distributed
#https_interface_host: 192.168.1.3
#https_interface_port: 9443
#https_interface_username: admin
#https_interface_password: admin
#resource_managers:
#  - { host: '192.168.1.1',
#      port: '9543',
#      username: 'admin',
#      password: 'admin'}
#  - { host: '192.168.1.2',
#      port: '9543',
#      username: 'admin',
#      password: 'admin'}

siddhi_api_keystore_file: ${carbon.home}/resources/security/wso2carbon.jks
siddhi_api_keystore_password: wso2carbon
siddhi_api_keystore_cert_password: wso2carbon

databridge_config_keystore_location: ${sys:carbon.home}/resources/security/wso2carbon.jks
databridge_config_keystore_password: wso2carbon

analytics_secure_vault_enabled: false # If sensitive passwords need to be encrypted enable this
securevault_privatekey_alias: wso2carbon
securevault_keystore_password: wso2carbon
securevault_privatekey_password: wso2carbon
securevault_keystore_location: ${sys:carbon.home}/resources/security/securevault.jks
securevault_secret_properties_file: ${sys:carbon.home}/conf/${sys:wso2.runtime}/secrets.properties
securevault_masterkeyreader_file: ${sys:carbon.home}/conf/${sys:wso2.runtime}/master-keys.yaml
securevault_persist_masterkeys_file: true

cluster_config_enabled: 'false'
cluster_config_group_id: sp
cluster_config_heartbeat_interval: 1000
cluster_config_max_retry: 2
cluster_config_event_polling_interval: 1000

# Key Store and Trust Store configuration
key_store_location: ${sys:carbon.home}/resources/security/wso2carbon.jks
key_store_password: wso2carbon
cert_password: wso2carbon
key_store_key_alias: wso2carbon
trust_store_location: ${sys:carbon.home}/resources/security/client-truststore.jks
trust_store_password: wso2carbon

databridge_config_worker_threads: 10
tcp_receiver_thread_pool_size: 100
ssl_receiver_thread_pool_size: 100

# Note: In below section if secure-vault is enabled and you have specified multile users otherthan the default user you need to update the secrests.properties file and and
# the deployment.yaml.j2 accordingly to accommodate secured values. 
# Authentication Configuration
authentication_type: local
authentication_admin_role: admin
user_store_users:
  - { username: 'admin',
      password: 'YWRtaW4=',
      roles: 1 }
user_store_roles:
  - { id: 1,
      displayName: 'admin' }

# Worker- List of configuration file templates, and the paths they should be written to
worker_config_files:
  - { src: 'carbon-home/conf/worker/deployment.yaml.j2',
      dest: '{{ carbon_home }}/conf/worker/deployment.yaml' }
  - { src: 'carbon-home/wso2/worker/bin/carbon.sh.j2',
      dest: '{{ carbon_home }}/wso2/worker/bin/carbon.sh' }
  - { src: 'carbon-home/conf/worker/secrets.properties.j2',
      dest: '{{ carbon_home }}/conf/worker/secrets.properties' }
  - { src: 'carbon-home/conf/worker/master-keys.yaml.j2',
      dest: '{{ carbon_home }}/conf/worker/master-keys.yaml' }

# Dashboard - List of configuration file templates, and the paths they should be written to
dashboard_config_files:
  - { src: 'carbon-home/conf/dashboard/deployment.yaml.j2',
      dest: '{{ carbon_home }}/conf/dashboard/deployment.yaml' }
  - { src: 'carbon-home/wso2/dashboard/bin/carbon.sh.j2',
      dest: '{{ carbon_home }}/wso2/dashboard/bin/carbon.sh' }
  - { src: 'carbon-home/conf/dashboard/secrets.properties.j2',
      dest: '{{ carbon_home }}/conf/dashboard/secrets.properties' }
  - { src: 'carbon-home/conf/dashboard/master-keys.yaml.j2',
      dest: '{{ carbon_home }}/conf/dashboard/master-keys.yaml' }
